### ISSUE TITLE
Bump to serverless v2.*

### ISSUE THREAD

**Issue by bushong1** [serverless-operations/serverless-apigateway-service-proxy#108]
Is there any tracking for a bump/migration to serverless v2.*?

**Comment by serverlesspolska** [comment]
I second that!

Also, why this plugin forces local installation of the Serverless Framework into `node_modules`?

```
npm i -D serverless-apigateway-service-proxy
npm WARN deprecated @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.

> protobufjs@6.10.1 postinstall /Users/pawel/ptc/oldportal/partner-credits/node_modules/protobufjs
> node scripts/postinstall


> serverless@1.83.2 postinstall /Users/pawel/ptc/oldportal/partner-credits/node_modules/serverless
> node ./scripts/postinstall.js
```
Version **serverless@1.83.2**

Basically, plugin it's not usable with > 2.0.0 version. I'm using 2.4.0.

Even after forcing local installation of serverless with 2.4.0 version I get error:

```
Serverless Error ---------------------------------------
 
  child "dynamodb" fails because ["dynamodb" must be an object]
 ```

**Comment by SauarvD** [comment]
Any update on this issue yet? Without forcing local installation, can't it work. I have version 2.15.0, but when using this plugin, it uses 1.83.0

**Comment by feg624** [comment]
I found the workaround of installing both serverless and serverless-apigateway-service-proxy within the local project, and also not installing serverless globally. Then I can run serverless via npx.

Not ideal, but helped me with the overlapping of versions.

**Comment by mfogel** [comment]
This plugin has serverless listed as a runtime dependency in `package.json`, which does not appear to be the standard way of doing things. I took a quick survey of the [most popular X serverless plugins](https://www.serverless.com/plugins/) to see how or if they list serverless in their `package.json`.

- [serverless-offline](https://github.com/dherault/serverless-offline/blob/master/package.json): as a `dev` and as a `peer` dependency
- [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack/blob/master/package.json): as a `dev` dependency
- [serverless-domain-manager](https://github.com/amplify-education/serverless-domain-manager/blob/master/package.json): as a `dev` dependency
- [serverless-prune-plugin](https://github.com/claygregory/serverless-prune-plugin/blob/master/package.json): not listed
- [serverless-http](https://github.com/dougmoscrop/serverless-http/blob/master/package.json): as a `dev` dependency
- [serverless-python-requirements](https://github.com/UnitedIncome/serverless-python-requirements/blob/master/package.json): not listed
- [serverless-plugin-tracing](https://github.com/alex-murashkin/serverless-plugin-tracing/blob/master/package.json): not listed
- [serverless-step-functions](https://github.com/serverless-operations/serverless-step-functions/blob/master/package.json): as a `dev` dependency

It looks like [eslint wants eslint plugins to list eslint as a `dev` dependency](https://github.com/eslint/generator-eslint/blob/master/plugin/templates/_package.json).

Other than this plugin, I have yet to see another plugin list serverless as a runtime dependency...

**Comment by serverlesspolska** [comment]
Is there any progress about that?

If maintainers of this great project have problems solving this dependency, maybe we could ask Serverless Framework team for help? There is a lot of refactoring going on in SF. Maybe it would be wise to ask them for guidance?

**Comment by PtkFerraro** [comment]
> I found the workaround of installing both serverless and serverless-apigateway-service-proxy within the local project, and also not installing serverless globally. Then I can run serverless via npx.
> 
> Not ideal, but helped me with the overlapping of versions.

Hi there! how did you force an upgrade locally? cheers

**Comment by feg624** [comment]
Hi there: I haven't been working on this for a few months, so I don't remember exactly whether I needed to force the update. I think I may have used the regular npm command to force one particular version of the library.

Regards,

Franco

________________________________
De: PtkF ***@***.***>
Enviado: lunes, 24 de mayo de 2021 22:01
Para: serverless-operations/serverless-apigateway-service-proxy ***@***.***>
Cc: Franco Guidoli ***@***.***>; Comment ***@***.***>
Asunto: Re: [serverless-operations/serverless-apigateway-service-proxy] Bump to serverless v2.* (#108)


I found the workaround of installing both serverless and serverless-apigateway-service-proxy within the local project, and also not installing serverless globally. Then I can run serverless via npx.

Not ideal, but helped me with the overlapping of versions.

Hi there! how did you force an upgrade locally? cheers

**Comment by ricardo-dlc** [comment]
Any updates on this? I have a repo with this plugin and adding serverless as a dependency in my project worked, but ideally I would like to use serverless globally instead og locally.

**Comment by iwaduarte** [comment]
Is there anyone here that could answer us ? Feels like it is abandoned.

**Comment by horike37** [comment]
Hi, thank you for pointing it out.
Unfortunately, I have forgotten why serverless is in dependencies Maybe, some functions within Serverless Framework core have been used in this plugin.

what I can say for sure is that if serverlessv2.0 moves into dev dependencies and then all unit and integration tests are passed, it works fine.

**Comment by mdunc** [comment]
Currently, if someone were to follow the documentation to set up Serverless and then later install this plugin, this plugin would downgrade them to a very old version of Serverless and their serverless.yml would no longer work.  I struggled with this yesterday and ultimately decided to use proxy Lambda functions since I don't know enough about npm and the nodejs ecosystem to troubleshoot this.

**Comment by pankajanand18** [comment]
I created this PR to migrate from SLS v1.x  to SLS v2.x  https://github.com/serverless-operations/serverless-apigateway-service-proxy/pull/144
Please let me know how is it looking or It requires something more to upgrade.

**Comment by pankajanand18** [comment]
Hi All, bumping the thread to get any feedback on the PR that I posted to upgrade to SLS 2.x version. 

@horike37  👆

**Comment by horike37** [comment]
@pankajanand18 
Thank you for pinging! I have released sls v2 support version.

**Comment by serverlesspolska** [comment]
Well done @horike37 & @pankajanand18 👏
Thank you for your work!
