### ISSUE TITLE
Compatibility with Serverless 3.x.x?

### ISSUE THREAD

**Issue by johnmee** [serverless-operations/serverless-apigateway-service-proxy#157]
Has anyone tried this with serverless 3?

peer dependancy is at:
    "serverless": "^2.69.1"

**Comment by ElderMael** [comment]
Yes. It won't work. We had to remove the plugin.

**Comment by johnmee** [comment]
Shame. Any guesses how much work is involved?

**Comment by corydorning** [comment]
following this as well, as i'd also like to use this with serverless 3.x as well.

**Comment by horike37** [comment]
The latest version of this plugin has been supported for serverless v3.

**Comment by johnmee** [comment]
Thanks Takahiro.  Much appreciated.
