### ISSUE TITLE
  this.provider.naming.getCloudFrontDistributionDomainNameLogicalId is not a function

### ISSUE THREAD

**Issue by gaurav-vs** [serverless-operations/serverless-apigateway-service-proxy#48]
After adding this module in my serveless, Everything is working fine but Serveless deployment throws this error

AddApiKey: Rest Api k5ot3da3wc already associated with the usage plan
Serverless: [AWS cloudformation 200 0.134s 0 retries] describeStacks({ StackName: 'tp-service-dev' })
 
  Type Error ---------------------------------------------
 
  this.provider.naming.getCloudFrontDistributionDomainNameLogicalId is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------

**Comment by tdahlin** [comment]
I had the same issue. Updated serverless and the error no longer occurs.
$sls --version
Framework Core: 1.58.0
Plugin: 3.2.5
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0

**Comment by asaghri** [comment]
I've updated to the Framework Core: 1.61.3 and the error is gone !
