### ISSUE TITLE
Support for request mapping template for SQS

### ISSUE THREAD

**Issue by devsatishm** [serverless-operations/serverless-apigateway-service-proxy#62]
Good work on the plugin!

Do you plan to support request mapping templates for SQS? 

We have a use-case where we need to expose a web-hook to our external teams to capture certain events. Each of these teams can send a different set of headers. Is there a way to capture complete set of headers & payload to push it to SQS?

Thanks!

**Comment by erezrokah** [comment]
Are you looking for something like this https://github.com/horike37/serverless-apigateway-service-proxy#customizing-api-gateway-parameters

You can enabled the headers `acceptParameters` and pass them as message attributes via `requestParameters `

**Comment by devsatishm** [comment]
@erezrokah I'm looking for request template customization like [this](https://github.com/horike37/serverless-apigateway-service-proxy#customizing-request-body-mapping-templates). I think `requestParameters` solution works if we always expect a specific set of headers (fixed header names). Also, I couldn't figure out how to send the  entire set of headers as part of  the message. Any  suggestions?

**Comment by erezrokah** [comment]
Regardless of how you transform the headers and pass them to the SQS service (template vs requestParameters) I think you still to allow them via `acceptParameters` to make them available.

If each team can send a different set of headers, you might want to have a different SQS service proxy for each team.

**Comment by devsatishm** [comment]
Thanks @erezrokah! Even if we go with different SQS proxy per team/customer, wouldn't it still require us to know header names in advance to add them to `acceptParameters`? Is there a cleaner way to not hardcode these header names and pass whatever comes as part of http request to the queue?

**Comment by horike37** [comment]
Closing this issue since this moved to #80
