### ISSUE TITLE
s3 integration response mappings

### ISSUE THREAD

**Issue by ed-sparkes** [serverless-operations/serverless-apigateway-service-proxy#65]
Is there a way via the plugin config to map integration response headers

Specifically for my S3 integration i wish to map the ETag and Cache-Control headers from my S3 objects so that clients can decide whether to actually re-request the asset from s3 or serve from its cache? 

In cloudformation this is possible but not evident from the documentation if the plugin at present supports this. 
```
method.response.header.Cache-Control: integration.response.header.Cache-Control
method.response.header.ETag: integration.response.header.ETag
```

Similarly, would require the forwarding of the If-None-Match header from the method request to the integration request

Many thanks, Ed

**Comment by horike37** [comment]
@ed-sparkes 
Thank you for opening this issue 👍 
Right now, That is not supported, the integration response headers is hardcoded as following.
https://github.com/serverless-operations/serverless-apigateway-service-proxy/blob/9212b17b73498248128d7b2111fb2c4e52e4c3d6/lib/package/s3/compileMethodsToS3.js#L102

I think would be great if that can be defined within serverless.yml.

**Comment by horike37** [comment]
related issue is #53

**Comment by horike37** [comment]
Closing this issue because of duplication.
