### ISSUE TITLE
Response templates for SQS integrations

### ISSUE THREAD

**Issue by sebto** [serverless-operations/serverless-apigateway-service-proxy#73]
Is there anyway to customize the response of SQS integration? Now it returns the result of SQS directly to the user which is in XML format and contains the message id. I need to return something in JSON format. I read the codes but it seems it does not support response templates for SQS.

**Comment by balsabojic** [comment]
As far as i read, they started with developing it for all proxies in #54 - maybe you can add comment or vote.

**Comment by horike37** [comment]
This feature has not still implemented yet since the above pr is just for Kinesis proxy. Closing once since moving this to #80.
