### ISSUE TITLE
DynamoDB Serialization error

### ISSUE THREAD

**Issue by sushrutpatnaik** [serverless-operations/serverless-apigateway-service-proxy#76]
I get serialization error if I give a nested JSON in the request Body for PUT request in dynamoDB. Does this plugin support nested JSON or I need to change the mapping template

**Comment by horike37** [comment]
Yes, This has not supported for nested JSON yet. 

> Does this plugin support nested JSON or I need to change the mapping template
Exactly.

#82 may make it possible.

Closing once. Feel free to reopen if you want to continue this discussion.
