### ISSUE TITLE
Plugin assumes `aws` partition so won't work in China / GovCloud

### ISSUE THREAD

**Issue by glb** [serverless-operations/serverless-apigateway-service-proxy#85]
The plugin constructs ARNs assuming that they will all be `arn:aws:...` (see [search results](https://github.com/serverless-operations/serverless-apigateway-service-proxy/search?q=%22arn%3Aaws%3A%22&unscoped_q=%22arn%3Aaws%3A%22)), but this is not always true.

You can use the [`AWS::Partition` pseudo-parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-partition) to determine the current partition.

Would you be open to a PR to help resolve this issue?

**Comment by horike37** [comment]
>Would you be open to a PR to help resolve this issue?

Yes! Great idea.
